// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxisvnykhkftetungtaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4aXN2bnlraGtmdGV0dW5ndGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDY2MDksImV4cCI6MjA3NDQ4MjYwOX0.WcGibMNlVwMRdhQZA1Xd2Ypk_uMTDrQWvXTd9myGdGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});